// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmJhWFuFvdlqeCKj0os4j70UJUDmQfHKE',
    appId: '1:960823061462:web:40e7421a95ac169b5b5277',
    messagingSenderId: '960823061462',
    projectId: 'campus-finder-bc900',
    authDomain: 'campus-finder-bc900.firebaseapp.com',
    databaseURL: 'https://campus-finder-bc900-default-rtdb.firebaseio.com',
    storageBucket: 'campus-finder-bc900.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTI5OxAqocLtB-IWyE1qTdRndCHWl7Rbs',
    appId: '1:960823061462:android:83f0ce01b225f4a35b5277',
    messagingSenderId: '960823061462',
    projectId: 'campus-finder-bc900',
    databaseURL: 'https://campus-finder-bc900-default-rtdb.firebaseio.com',
    storageBucket: 'campus-finder-bc900.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVHF7n9qo0g0I1aaaiwRskVpe-y44NmrU',
    appId: '1:960823061462:ios:a2a72db953e1f5035b5277',
    messagingSenderId: '960823061462',
    projectId: 'campus-finder-bc900',
    databaseURL: 'https://campus-finder-bc900-default-rtdb.firebaseio.com',
    storageBucket: 'campus-finder-bc900.firebasestorage.app',
    iosBundleId: 'com.example.campusfinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVHF7n9qo0g0I1aaaiwRskVpe-y44NmrU',
    appId: '1:960823061462:ios:a2a72db953e1f5035b5277',
    messagingSenderId: '960823061462',
    projectId: 'campus-finder-bc900',
    databaseURL: 'https://campus-finder-bc900-default-rtdb.firebaseio.com',
    storageBucket: 'campus-finder-bc900.firebasestorage.app',
    iosBundleId: 'com.example.campusfinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmJhWFuFvdlqeCKj0os4j70UJUDmQfHKE',
    appId: '1:960823061462:web:345f73276f0d37ac5b5277',
    messagingSenderId: '960823061462',
    projectId: 'campus-finder-bc900',
    authDomain: 'campus-finder-bc900.firebaseapp.com',
    databaseURL: 'https://campus-finder-bc900-default-rtdb.firebaseio.com',
    storageBucket: 'campus-finder-bc900.firebasestorage.app',
  );
}
